//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  siteSettings: SiteSettings;
  siteSettingsConnection: SiteSettingsConnection;
  products: Products;
  productsConnection: ProductsConnection;
  cyberPets: CyberPets;
  cyberPetsConnection: CyberPetsConnection;
  cyberItems: CyberItems;
  cyberItemsConnection: CyberItemsConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteSettingsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteSettingsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteSettingsFilter>;
};


export type QueryProductsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProductsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProductsFilter>;
};


export type QueryCyberPetsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryCyberPetsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CyberPetsFilter>;
};


export type QueryCyberItemsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryCyberItemsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CyberItemsFilter>;
};

export type DocumentFilter = {
  siteSettings?: InputMaybe<SiteSettingsFilter>;
  products?: InputMaybe<ProductsFilter>;
  cyberPets?: InputMaybe<CyberPetsFilter>;
  cyberItems?: InputMaybe<CyberItemsFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = SiteSettings | Products | CyberPets | CyberItems | Folder;

export type SiteSettings = Node & Document & {
  __typename?: 'SiteSettings';
  theme?: Maybe<Scalars['String']['output']>;
  heroTitleZh?: Maybe<Scalars['String']['output']>;
  heroTitleEn?: Maybe<Scalars['String']['output']>;
  paymentMethod?: Maybe<Scalars['String']['output']>;
  paymentAccount?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type SiteSettingsFilter = {
  theme?: InputMaybe<StringFilter>;
  heroTitleZh?: InputMaybe<StringFilter>;
  heroTitleEn?: InputMaybe<StringFilter>;
  paymentMethod?: InputMaybe<StringFilter>;
  paymentAccount?: InputMaybe<StringFilter>;
};

export type SiteSettingsConnectionEdges = {
  __typename?: 'SiteSettingsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<SiteSettings>;
};

export type SiteSettingsConnection = Connection & {
  __typename?: 'SiteSettingsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SiteSettingsConnectionEdges>>>;
};

export type ProductsItems = {
  __typename?: 'ProductsItems';
  id: Scalars['String']['output'];
  nameZh: Scalars['String']['output'];
  nameEn: Scalars['String']['output'];
  descZh?: Maybe<Scalars['String']['output']>;
  descEn?: Maybe<Scalars['String']['output']>;
  category?: Maybe<Scalars['String']['output']>;
  price: Scalars['Float']['output'];
  image?: Maybe<Scalars['String']['output']>;
};

export type Products = Node & Document & {
  __typename?: 'Products';
  items?: Maybe<Array<Maybe<ProductsItems>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type ProductsItemsFilter = {
  id?: InputMaybe<StringFilter>;
  nameZh?: InputMaybe<StringFilter>;
  nameEn?: InputMaybe<StringFilter>;
  descZh?: InputMaybe<StringFilter>;
  descEn?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  price?: InputMaybe<NumberFilter>;
  image?: InputMaybe<StringFilter>;
};

export type ProductsFilter = {
  items?: InputMaybe<ProductsItemsFilter>;
};

export type ProductsConnectionEdges = {
  __typename?: 'ProductsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Products>;
};

export type ProductsConnection = Connection & {
  __typename?: 'ProductsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ProductsConnectionEdges>>>;
};

export type CyberPetsItems = {
  __typename?: 'CyberPetsItems';
  id: Scalars['String']['output'];
  nameZh: Scalars['String']['output'];
  nameEn: Scalars['String']['output'];
  icon?: Maybe<Scalars['String']['output']>;
  palette?: Maybe<Scalars['String']['output']>;
  price?: Maybe<Scalars['Float']['output']>;
  mood?: Maybe<Scalars['Float']['output']>;
  energy?: Maybe<Scalars['Float']['output']>;
};

export type CyberPets = Node & Document & {
  __typename?: 'CyberPets';
  items?: Maybe<Array<Maybe<CyberPetsItems>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type CyberPetsItemsFilter = {
  id?: InputMaybe<StringFilter>;
  nameZh?: InputMaybe<StringFilter>;
  nameEn?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
  palette?: InputMaybe<StringFilter>;
  price?: InputMaybe<NumberFilter>;
  mood?: InputMaybe<NumberFilter>;
  energy?: InputMaybe<NumberFilter>;
};

export type CyberPetsFilter = {
  items?: InputMaybe<CyberPetsItemsFilter>;
};

export type CyberPetsConnectionEdges = {
  __typename?: 'CyberPetsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<CyberPets>;
};

export type CyberPetsConnection = Connection & {
  __typename?: 'CyberPetsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<CyberPetsConnectionEdges>>>;
};

export type CyberItemsItems = {
  __typename?: 'CyberItemsItems';
  id: Scalars['String']['output'];
  type?: Maybe<Scalars['String']['output']>;
  nameZh: Scalars['String']['output'];
  nameEn: Scalars['String']['output'];
  price?: Maybe<Scalars['Float']['output']>;
  palette?: Maybe<Scalars['String']['output']>;
  energy?: Maybe<Scalars['Float']['output']>;
};

export type CyberItems = Node & Document & {
  __typename?: 'CyberItems';
  items?: Maybe<Array<Maybe<CyberItemsItems>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type CyberItemsItemsFilter = {
  id?: InputMaybe<StringFilter>;
  type?: InputMaybe<StringFilter>;
  nameZh?: InputMaybe<StringFilter>;
  nameEn?: InputMaybe<StringFilter>;
  price?: InputMaybe<NumberFilter>;
  palette?: InputMaybe<StringFilter>;
  energy?: InputMaybe<NumberFilter>;
};

export type CyberItemsFilter = {
  items?: InputMaybe<CyberItemsItemsFilter>;
};

export type CyberItemsConnectionEdges = {
  __typename?: 'CyberItemsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<CyberItems>;
};

export type CyberItemsConnection = Connection & {
  __typename?: 'CyberItemsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<CyberItemsConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateSiteSettings: SiteSettings;
  createSiteSettings: SiteSettings;
  updateProducts: Products;
  createProducts: Products;
  updateCyberPets: CyberPets;
  createCyberPets: CyberPets;
  updateCyberItems: CyberItems;
  createCyberItems: CyberItems;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateSiteSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteSettingsMutation;
};


export type MutationCreateSiteSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteSettingsMutation;
};


export type MutationUpdateProductsArgs = {
  relativePath: Scalars['String']['input'];
  params: ProductsMutation;
};


export type MutationCreateProductsArgs = {
  relativePath: Scalars['String']['input'];
  params: ProductsMutation;
};


export type MutationUpdateCyberPetsArgs = {
  relativePath: Scalars['String']['input'];
  params: CyberPetsMutation;
};


export type MutationCreateCyberPetsArgs = {
  relativePath: Scalars['String']['input'];
  params: CyberPetsMutation;
};


export type MutationUpdateCyberItemsArgs = {
  relativePath: Scalars['String']['input'];
  params: CyberItemsMutation;
};


export type MutationCreateCyberItemsArgs = {
  relativePath: Scalars['String']['input'];
  params: CyberItemsMutation;
};

export type DocumentUpdateMutation = {
  siteSettings?: InputMaybe<SiteSettingsMutation>;
  products?: InputMaybe<ProductsMutation>;
  cyberPets?: InputMaybe<CyberPetsMutation>;
  cyberItems?: InputMaybe<CyberItemsMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  siteSettings?: InputMaybe<SiteSettingsMutation>;
  products?: InputMaybe<ProductsMutation>;
  cyberPets?: InputMaybe<CyberPetsMutation>;
  cyberItems?: InputMaybe<CyberItemsMutation>;
};

export type SiteSettingsMutation = {
  theme?: InputMaybe<Scalars['String']['input']>;
  heroTitleZh?: InputMaybe<Scalars['String']['input']>;
  heroTitleEn?: InputMaybe<Scalars['String']['input']>;
  paymentMethod?: InputMaybe<Scalars['String']['input']>;
  paymentAccount?: InputMaybe<Scalars['String']['input']>;
};

export type ProductsItemsMutation = {
  id?: InputMaybe<Scalars['String']['input']>;
  nameZh?: InputMaybe<Scalars['String']['input']>;
  nameEn?: InputMaybe<Scalars['String']['input']>;
  descZh?: InputMaybe<Scalars['String']['input']>;
  descEn?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['Float']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
};

export type ProductsMutation = {
  items?: InputMaybe<Array<InputMaybe<ProductsItemsMutation>>>;
};

export type CyberPetsItemsMutation = {
  id?: InputMaybe<Scalars['String']['input']>;
  nameZh?: InputMaybe<Scalars['String']['input']>;
  nameEn?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
  palette?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['Float']['input']>;
  mood?: InputMaybe<Scalars['Float']['input']>;
  energy?: InputMaybe<Scalars['Float']['input']>;
};

export type CyberPetsMutation = {
  items?: InputMaybe<Array<InputMaybe<CyberPetsItemsMutation>>>;
};

export type CyberItemsItemsMutation = {
  id?: InputMaybe<Scalars['String']['input']>;
  type?: InputMaybe<Scalars['String']['input']>;
  nameZh?: InputMaybe<Scalars['String']['input']>;
  nameEn?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['Float']['input']>;
  palette?: InputMaybe<Scalars['String']['input']>;
  energy?: InputMaybe<Scalars['Float']['input']>;
};

export type CyberItemsMutation = {
  items?: InputMaybe<Array<InputMaybe<CyberItemsItemsMutation>>>;
};

export type SiteSettingsPartsFragment = { __typename: 'SiteSettings', theme?: string | null, heroTitleZh?: string | null, heroTitleEn?: string | null, paymentMethod?: string | null, paymentAccount?: string | null };

export type ProductsPartsFragment = { __typename: 'Products', items?: Array<{ __typename: 'ProductsItems', id: string, nameZh: string, nameEn: string, descZh?: string | null, descEn?: string | null, category?: string | null, price: number, image?: string | null } | null> | null };

export type CyberPetsPartsFragment = { __typename: 'CyberPets', items?: Array<{ __typename: 'CyberPetsItems', id: string, nameZh: string, nameEn: string, icon?: string | null, palette?: string | null, price?: number | null, mood?: number | null, energy?: number | null } | null> | null };

export type CyberItemsPartsFragment = { __typename: 'CyberItems', items?: Array<{ __typename: 'CyberItemsItems', id: string, type?: string | null, nameZh: string, nameEn: string, price?: number | null, palette?: string | null, energy?: number | null } | null> | null };

export type SiteSettingsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SiteSettingsQuery = { __typename?: 'Query', siteSettings: { __typename: 'SiteSettings', id: string, theme?: string | null, heroTitleZh?: string | null, heroTitleEn?: string | null, paymentMethod?: string | null, paymentAccount?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type SiteSettingsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteSettingsFilter>;
}>;


export type SiteSettingsConnectionQuery = { __typename?: 'Query', siteSettingsConnection: { __typename?: 'SiteSettingsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SiteSettingsConnectionEdges', cursor: string, node?: { __typename: 'SiteSettings', id: string, theme?: string | null, heroTitleZh?: string | null, heroTitleEn?: string | null, paymentMethod?: string | null, paymentAccount?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ProductsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ProductsQuery = { __typename?: 'Query', products: { __typename: 'Products', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'ProductsItems', id: string, nameZh: string, nameEn: string, descZh?: string | null, descEn?: string | null, category?: string | null, price: number, image?: string | null } | null> | null } };

export type ProductsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProductsFilter>;
}>;


export type ProductsConnectionQuery = { __typename?: 'Query', productsConnection: { __typename?: 'ProductsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ProductsConnectionEdges', cursor: string, node?: { __typename: 'Products', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'ProductsItems', id: string, nameZh: string, nameEn: string, descZh?: string | null, descEn?: string | null, category?: string | null, price: number, image?: string | null } | null> | null } | null } | null> | null } };

export type CyberPetsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type CyberPetsQuery = { __typename?: 'Query', cyberPets: { __typename: 'CyberPets', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'CyberPetsItems', id: string, nameZh: string, nameEn: string, icon?: string | null, palette?: string | null, price?: number | null, mood?: number | null, energy?: number | null } | null> | null } };

export type CyberPetsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CyberPetsFilter>;
}>;


export type CyberPetsConnectionQuery = { __typename?: 'Query', cyberPetsConnection: { __typename?: 'CyberPetsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'CyberPetsConnectionEdges', cursor: string, node?: { __typename: 'CyberPets', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'CyberPetsItems', id: string, nameZh: string, nameEn: string, icon?: string | null, palette?: string | null, price?: number | null, mood?: number | null, energy?: number | null } | null> | null } | null } | null> | null } };

export type CyberItemsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type CyberItemsQuery = { __typename?: 'Query', cyberItems: { __typename: 'CyberItems', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'CyberItemsItems', id: string, type?: string | null, nameZh: string, nameEn: string, price?: number | null, palette?: string | null, energy?: number | null } | null> | null } };

export type CyberItemsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CyberItemsFilter>;
}>;


export type CyberItemsConnectionQuery = { __typename?: 'Query', cyberItemsConnection: { __typename?: 'CyberItemsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'CyberItemsConnectionEdges', cursor: string, node?: { __typename: 'CyberItems', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'CyberItemsItems', id: string, type?: string | null, nameZh: string, nameEn: string, price?: number | null, palette?: string | null, energy?: number | null } | null> | null } | null } | null> | null } };

export const SiteSettingsPartsFragmentDoc = gql`
    fragment SiteSettingsParts on SiteSettings {
  __typename
  theme
  heroTitleZh
  heroTitleEn
  paymentMethod
  paymentAccount
}
    `;
export const ProductsPartsFragmentDoc = gql`
    fragment ProductsParts on Products {
  __typename
  items {
    __typename
    id
    nameZh
    nameEn
    descZh
    descEn
    category
    price
    image
  }
}
    `;
export const CyberPetsPartsFragmentDoc = gql`
    fragment CyberPetsParts on CyberPets {
  __typename
  items {
    __typename
    id
    nameZh
    nameEn
    icon
    palette
    price
    mood
    energy
  }
}
    `;
export const CyberItemsPartsFragmentDoc = gql`
    fragment CyberItemsParts on CyberItems {
  __typename
  items {
    __typename
    id
    type
    nameZh
    nameEn
    price
    palette
    energy
  }
}
    `;
export const SiteSettingsDocument = gql`
    query siteSettings($relativePath: String!) {
  siteSettings(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SiteSettingsParts
  }
}
    ${SiteSettingsPartsFragmentDoc}`;
export const SiteSettingsConnectionDocument = gql`
    query siteSettingsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SiteSettingsFilter) {
  siteSettingsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SiteSettingsParts
      }
    }
  }
}
    ${SiteSettingsPartsFragmentDoc}`;
export const ProductsDocument = gql`
    query products($relativePath: String!) {
  products(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ProductsParts
  }
}
    ${ProductsPartsFragmentDoc}`;
export const ProductsConnectionDocument = gql`
    query productsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ProductsFilter) {
  productsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ProductsParts
      }
    }
  }
}
    ${ProductsPartsFragmentDoc}`;
export const CyberPetsDocument = gql`
    query cyberPets($relativePath: String!) {
  cyberPets(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...CyberPetsParts
  }
}
    ${CyberPetsPartsFragmentDoc}`;
export const CyberPetsConnectionDocument = gql`
    query cyberPetsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: CyberPetsFilter) {
  cyberPetsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...CyberPetsParts
      }
    }
  }
}
    ${CyberPetsPartsFragmentDoc}`;
export const CyberItemsDocument = gql`
    query cyberItems($relativePath: String!) {
  cyberItems(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...CyberItemsParts
  }
}
    ${CyberItemsPartsFragmentDoc}`;
export const CyberItemsConnectionDocument = gql`
    query cyberItemsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: CyberItemsFilter) {
  cyberItemsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...CyberItemsParts
      }
    }
  }
}
    ${CyberItemsPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      siteSettings(variables: SiteSettingsQueryVariables, options?: C): Promise<{data: SiteSettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteSettingsQueryVariables, query: string}> {
        return requester<{data: SiteSettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteSettingsQueryVariables, query: string}, SiteSettingsQueryVariables>(SiteSettingsDocument, variables, options);
      },
    siteSettingsConnection(variables?: SiteSettingsConnectionQueryVariables, options?: C): Promise<{data: SiteSettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteSettingsConnectionQueryVariables, query: string}> {
        return requester<{data: SiteSettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteSettingsConnectionQueryVariables, query: string}, SiteSettingsConnectionQueryVariables>(SiteSettingsConnectionDocument, variables, options);
      },
    products(variables: ProductsQueryVariables, options?: C): Promise<{data: ProductsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProductsQueryVariables, query: string}> {
        return requester<{data: ProductsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProductsQueryVariables, query: string}, ProductsQueryVariables>(ProductsDocument, variables, options);
      },
    productsConnection(variables?: ProductsConnectionQueryVariables, options?: C): Promise<{data: ProductsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProductsConnectionQueryVariables, query: string}> {
        return requester<{data: ProductsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProductsConnectionQueryVariables, query: string}, ProductsConnectionQueryVariables>(ProductsConnectionDocument, variables, options);
      },
    cyberPets(variables: CyberPetsQueryVariables, options?: C): Promise<{data: CyberPetsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CyberPetsQueryVariables, query: string}> {
        return requester<{data: CyberPetsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CyberPetsQueryVariables, query: string}, CyberPetsQueryVariables>(CyberPetsDocument, variables, options);
      },
    cyberPetsConnection(variables?: CyberPetsConnectionQueryVariables, options?: C): Promise<{data: CyberPetsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CyberPetsConnectionQueryVariables, query: string}> {
        return requester<{data: CyberPetsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CyberPetsConnectionQueryVariables, query: string}, CyberPetsConnectionQueryVariables>(CyberPetsConnectionDocument, variables, options);
      },
    cyberItems(variables: CyberItemsQueryVariables, options?: C): Promise<{data: CyberItemsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CyberItemsQueryVariables, query: string}> {
        return requester<{data: CyberItemsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CyberItemsQueryVariables, query: string}, CyberItemsQueryVariables>(CyberItemsDocument, variables, options);
      },
    cyberItemsConnection(variables?: CyberItemsConnectionQueryVariables, options?: C): Promise<{data: CyberItemsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CyberItemsConnectionQueryVariables, query: string}> {
        return requester<{data: CyberItemsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CyberItemsConnectionQueryVariables, query: string}, CyberItemsConnectionQueryVariables>(CyberItemsConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/2.4/content/local/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  